//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ryanstaurant.Clients.WPF.ManagementCenter.Model.UMSProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UMSProxy.IUMSService")]
    public interface IUMSService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUMSService/GetEmployees", ReplyAction="http://tempuri.org/IUMSService/GetEmployeesResponse")]
        Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.Employee[]> GetEmployees(Ryanstaurant.UMS.DataContract.Employee[] employees);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUMSService/AddEmployees", ReplyAction="http://tempuri.org/IUMSService/AddEmployeesResponse")]
        Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.Employee[]> AddEmployees(Ryanstaurant.UMS.DataContract.Employee[] employees);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUMSService/ModifyEmployees", ReplyAction="http://tempuri.org/IUMSService/ModifyEmployeesResponse")]
        Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.Employee[]> ModifyEmployees(Ryanstaurant.UMS.DataContract.Employee[] employees);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUMSService/DeleteEmployees", ReplyAction="http://tempuri.org/IUMSService/DeleteEmployeesResponse")]
        Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.Employee[]> DeleteEmployees(Ryanstaurant.UMS.DataContract.Employee[] employees);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUMSService/GetRoles", ReplyAction="http://tempuri.org/IUMSService/GetRolesResponse")]
        Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.Role[]> GetRoles(Ryanstaurant.UMS.DataContract.Role[] roles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUMSService/AddRoles", ReplyAction="http://tempuri.org/IUMSService/AddRolesResponse")]
        Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.Role[]> AddRoles(Ryanstaurant.UMS.DataContract.Role[] roles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUMSService/ModifyRoles", ReplyAction="http://tempuri.org/IUMSService/ModifyRolesResponse")]
        Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.Role[]> ModifyRoles(Ryanstaurant.UMS.DataContract.Role[] roles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUMSService/DeleteRoles", ReplyAction="http://tempuri.org/IUMSService/DeleteRolesResponse")]
        Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.Role[]> DeleteRoles(Ryanstaurant.UMS.DataContract.Role[] roles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUMSService/GetAuthorities", ReplyAction="http://tempuri.org/IUMSService/GetAuthoritiesResponse")]
        Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.Authority[]> GetAuthorities(Ryanstaurant.UMS.DataContract.Authority[] authorities);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUMSService/AddAuthorities", ReplyAction="http://tempuri.org/IUMSService/AddAuthoritiesResponse")]
        Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.Authority[]> AddAuthorities(Ryanstaurant.UMS.DataContract.Authority[] authorities);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUMSService/ModifyAuthorities", ReplyAction="http://tempuri.org/IUMSService/ModifyAuthoritiesResponse")]
        Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.Authority[]> ModifyAuthorities(Ryanstaurant.UMS.DataContract.Authority[] authorities);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUMSService/DeleteAuthorities", ReplyAction="http://tempuri.org/IUMSService/DeleteAuthoritiesResponse")]
        Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.Authority[]> DeleteAuthorities(Ryanstaurant.UMS.DataContract.Authority[] authorities);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUMSService/GetEmpRoles", ReplyAction="http://tempuri.org/IUMSService/GetEmpRolesResponse")]
        Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.EmpRole[]> GetEmpRoles(Ryanstaurant.UMS.DataContract.EmpRole[] empRoles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUMSService/AddEmpRoles", ReplyAction="http://tempuri.org/IUMSService/AddEmpRolesResponse")]
        Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.EmpRole[]> AddEmpRoles(Ryanstaurant.UMS.DataContract.EmpRole[] empRoles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUMSService/ModifyEmpRoles", ReplyAction="http://tempuri.org/IUMSService/ModifyEmpRolesResponse")]
        Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.EmpRole[]> ModifyEmpRoles(Ryanstaurant.UMS.DataContract.EmpRole[] empRoles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUMSService/DeleteEmpRoles", ReplyAction="http://tempuri.org/IUMSService/DeleteEmpRolesResponse")]
        Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.EmpRole[]> DeleteEmpRoles(Ryanstaurant.UMS.DataContract.EmpRole[] empRoles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUMSService/GetRolAuths", ReplyAction="http://tempuri.org/IUMSService/GetRolAuthsResponse")]
        Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.RoleAuth[]> GetRolAuths(Ryanstaurant.UMS.DataContract.RoleAuth[] roleAuths);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUMSService/AddRolAuths", ReplyAction="http://tempuri.org/IUMSService/AddRolAuthsResponse")]
        Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.RoleAuth[]> AddRolAuths(Ryanstaurant.UMS.DataContract.RoleAuth[] roleAuths);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUMSService/ModifyRolAuths", ReplyAction="http://tempuri.org/IUMSService/ModifyRolAuthsResponse")]
        Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.RoleAuth[]> ModifyRolAuths(Ryanstaurant.UMS.DataContract.RoleAuth[] roleAuths);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUMSService/DeleteRolAuths", ReplyAction="http://tempuri.org/IUMSService/DeleteRolAuthsResponse")]
        Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.RoleAuth[]> DeleteRolAuths(Ryanstaurant.UMS.DataContract.RoleAuth[] roleAuths);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUMSService/GetEmpAuths", ReplyAction="http://tempuri.org/IUMSService/GetEmpAuthsResponse")]
        Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.EmpAuth[]> GetEmpAuths(Ryanstaurant.UMS.DataContract.EmpAuth[] empAuths);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUMSService/AddEmpAuths", ReplyAction="http://tempuri.org/IUMSService/AddEmpAuthsResponse")]
        Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.EmpAuth[]> AddEmpAuths(Ryanstaurant.UMS.DataContract.EmpAuth[] empAuths);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUMSService/ModifyEmpAuths", ReplyAction="http://tempuri.org/IUMSService/ModifyEmpAuthsResponse")]
        Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.EmpAuth[]> ModifyEmpAuths(Ryanstaurant.UMS.DataContract.EmpAuth[] empAuths);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUMSService/DeleteEmpAuths", ReplyAction="http://tempuri.org/IUMSService/DeleteEmpAuthsResponse")]
        Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.EmpAuth[]> DeleteEmpAuths(Ryanstaurant.UMS.DataContract.EmpAuth[] empAuths);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUMSServiceChannel : Ryanstaurant.Clients.WPF.ManagementCenter.Model.UMSProxy.IUMSService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UMSServiceClient : System.ServiceModel.ClientBase<Ryanstaurant.Clients.WPF.ManagementCenter.Model.UMSProxy.IUMSService>, Ryanstaurant.Clients.WPF.ManagementCenter.Model.UMSProxy.IUMSService {
        
        public UMSServiceClient() {
        }
        
        public UMSServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UMSServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UMSServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UMSServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.Employee[]> GetEmployees(Ryanstaurant.UMS.DataContract.Employee[] employees) {
            return base.Channel.GetEmployees(employees);
        }
        
        public Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.Employee[]> AddEmployees(Ryanstaurant.UMS.DataContract.Employee[] employees) {
            return base.Channel.AddEmployees(employees);
        }
        
        public Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.Employee[]> ModifyEmployees(Ryanstaurant.UMS.DataContract.Employee[] employees) {
            return base.Channel.ModifyEmployees(employees);
        }
        
        public Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.Employee[]> DeleteEmployees(Ryanstaurant.UMS.DataContract.Employee[] employees) {
            return base.Channel.DeleteEmployees(employees);
        }
        
        public Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.Role[]> GetRoles(Ryanstaurant.UMS.DataContract.Role[] roles) {
            return base.Channel.GetRoles(roles);
        }
        
        public Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.Role[]> AddRoles(Ryanstaurant.UMS.DataContract.Role[] roles) {
            return base.Channel.AddRoles(roles);
        }
        
        public Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.Role[]> ModifyRoles(Ryanstaurant.UMS.DataContract.Role[] roles) {
            return base.Channel.ModifyRoles(roles);
        }
        
        public Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.Role[]> DeleteRoles(Ryanstaurant.UMS.DataContract.Role[] roles) {
            return base.Channel.DeleteRoles(roles);
        }
        
        public Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.Authority[]> GetAuthorities(Ryanstaurant.UMS.DataContract.Authority[] authorities) {
            return base.Channel.GetAuthorities(authorities);
        }
        
        public Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.Authority[]> AddAuthorities(Ryanstaurant.UMS.DataContract.Authority[] authorities) {
            return base.Channel.AddAuthorities(authorities);
        }
        
        public Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.Authority[]> ModifyAuthorities(Ryanstaurant.UMS.DataContract.Authority[] authorities) {
            return base.Channel.ModifyAuthorities(authorities);
        }
        
        public Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.Authority[]> DeleteAuthorities(Ryanstaurant.UMS.DataContract.Authority[] authorities) {
            return base.Channel.DeleteAuthorities(authorities);
        }
        
        public Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.EmpRole[]> GetEmpRoles(Ryanstaurant.UMS.DataContract.EmpRole[] empRoles) {
            return base.Channel.GetEmpRoles(empRoles);
        }
        
        public Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.EmpRole[]> AddEmpRoles(Ryanstaurant.UMS.DataContract.EmpRole[] empRoles) {
            return base.Channel.AddEmpRoles(empRoles);
        }
        
        public Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.EmpRole[]> ModifyEmpRoles(Ryanstaurant.UMS.DataContract.EmpRole[] empRoles) {
            return base.Channel.ModifyEmpRoles(empRoles);
        }
        
        public Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.EmpRole[]> DeleteEmpRoles(Ryanstaurant.UMS.DataContract.EmpRole[] empRoles) {
            return base.Channel.DeleteEmpRoles(empRoles);
        }
        
        public Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.RoleAuth[]> GetRolAuths(Ryanstaurant.UMS.DataContract.RoleAuth[] roleAuths) {
            return base.Channel.GetRolAuths(roleAuths);
        }
        
        public Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.RoleAuth[]> AddRolAuths(Ryanstaurant.UMS.DataContract.RoleAuth[] roleAuths) {
            return base.Channel.AddRolAuths(roleAuths);
        }
        
        public Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.RoleAuth[]> ModifyRolAuths(Ryanstaurant.UMS.DataContract.RoleAuth[] roleAuths) {
            return base.Channel.ModifyRolAuths(roleAuths);
        }
        
        public Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.RoleAuth[]> DeleteRolAuths(Ryanstaurant.UMS.DataContract.RoleAuth[] roleAuths) {
            return base.Channel.DeleteRolAuths(roleAuths);
        }
        
        public Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.EmpAuth[]> GetEmpAuths(Ryanstaurant.UMS.DataContract.EmpAuth[] empAuths) {
            return base.Channel.GetEmpAuths(empAuths);
        }
        
        public Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.EmpAuth[]> AddEmpAuths(Ryanstaurant.UMS.DataContract.EmpAuth[] empAuths) {
            return base.Channel.AddEmpAuths(empAuths);
        }
        
        public Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.EmpAuth[]> ModifyEmpAuths(Ryanstaurant.UMS.DataContract.EmpAuth[] empAuths) {
            return base.Channel.ModifyEmpAuths(empAuths);
        }
        
        public Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.EmpAuth[]> DeleteEmpAuths(Ryanstaurant.UMS.DataContract.EmpAuth[] empAuths) {
            return base.Channel.DeleteEmpAuths(empAuths);
        }
    }
}
