//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ryanstaurant.UMS.DataAccess.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ryanstaurantEntities : DbContext
    {
        public ryanstaurantEntities()
            : base("name=ryanstaurantEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<authority> authority { get; set; }
        public virtual DbSet<Dishes> Dishes { get; set; }
        public virtual DbSet<emp_role> emp_role { get; set; }
        public virtual DbSet<employee> employee { get; set; }
        public virtual DbSet<menu> menu { get; set; }
        public virtual DbSet<navigator> navigator { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<seatimageconfig> seatimageconfig { get; set; }
        public virtual DbSet<SeatList> SeatList { get; set; }
        public virtual DbSet<sysconfig> sysconfig { get; set; }
        public virtual DbSet<table_seats> table_seats { get; set; }
        public virtual DbSet<tableimageconfig> tableimageconfig { get; set; }
        public virtual DbSet<tablelist> tablelist { get; set; }
    }
}
