//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ryanstaurant.UMS.DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tablelist
    {
        public int ID { get; set; }
        public string DisplayNo { get; set; }
        public Nullable<int> PosX { get; set; }
        public Nullable<int> PosY { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Length { get; set; }
    }
}
