//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ryanstaurant.Clients.ManagementCenter.Proxy.UMS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Proxy.UMS.IUMSService")]
    public interface IUMSService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUMSService/GetAllEmployees", ReplyAction="http://tempuri.org/IUMSService/GetAllEmployeesResponse")]
        Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.Employee[]> GetAllEmployees();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUMSService/GetEmployees", ReplyAction="http://tempuri.org/IUMSService/GetEmployeesResponse")]
        Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.Employee[]> GetEmployees(Ryanstaurant.UMS.DataContract.Employee[] employees);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUMSService/AddEmployees", ReplyAction="http://tempuri.org/IUMSService/AddEmployeesResponse")]
        Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.Employee[]> AddEmployees(Ryanstaurant.UMS.DataContract.Employee[] employees);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUMSService/ModifyEmployees", ReplyAction="http://tempuri.org/IUMSService/ModifyEmployeesResponse")]
        Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.Employee[]> ModifyEmployees(Ryanstaurant.UMS.DataContract.Employee[] employees);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUMSService/DeleteEmployees", ReplyAction="http://tempuri.org/IUMSService/DeleteEmployeesResponse")]
        Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.Employee[]> DeleteEmployees(Ryanstaurant.UMS.DataContract.Employee[] employees);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUMSServiceChannel : Ryanstaurant.Clients.ManagementCenter.Proxy.UMS.IUMSService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UMSServiceClient : System.ServiceModel.ClientBase<Ryanstaurant.Clients.ManagementCenter.Proxy.UMS.IUMSService>, Ryanstaurant.Clients.ManagementCenter.Proxy.UMS.IUMSService {
        
        public UMSServiceClient() {
        }
        
        public UMSServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UMSServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UMSServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UMSServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.Employee[]> GetAllEmployees() {
            return base.Channel.GetAllEmployees();
        }
        
        public Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.Employee[]> GetEmployees(Ryanstaurant.UMS.DataContract.Employee[] employees) {
            return base.Channel.GetEmployees(employees);
        }
        
        public Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.Employee[]> AddEmployees(Ryanstaurant.UMS.DataContract.Employee[] employees) {
            return base.Channel.AddEmployees(employees);
        }
        
        public Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.Employee[]> ModifyEmployees(Ryanstaurant.UMS.DataContract.Employee[] employees) {
            return base.Channel.ModifyEmployees(employees);
        }
        
        public Ryanstaurant.UMS.DataContract.Utility.ResultEntity<Ryanstaurant.UMS.DataContract.Employee[]> DeleteEmployees(Ryanstaurant.UMS.DataContract.Employee[] employees) {
            return base.Channel.DeleteEmployees(employees);
        }
    }
}
